title: "Hybrid Dropdown - a better alaternative to <select/> fields"
description: Build powerful customised styled dropdown fields with filtrable list of options for your forms
remote_theme: pmarsceill/just-the-docs
#color_scheme: light
#search_enabled: true
#heading_anchors: true
